### PR TITLE
Add Jenkinsfile and gitignore

### PR DESCRIPTION
**Pull request by ligangty**

### CODE REVIEW

**Comment by rnc** [comment]
Is this for some internal Jenkins? Why not setup a GitHub Actions workflow instead?

**Comment by ligangty** [comment]
@rnc We have an internal indy to host all snapshot version with each PR build merging to publish dependency for internal usage. Of course the github action sounds good too, will add later.

**Comment by ligangty** [comment]
Oh, just found another PR for github actions. :-)

**Comment by rnc** [comment]
> @rnc We have an internal indy to host all snapshot version with each PR build merging to publish dependency for internal usage. Of course the github action sounds good too, will add later.

What I do for other repos I control is simply publish each snapshot to sonatype snapshots repo via github actions - this removed the need for any internal jenkins/repository hosting/etc. And the snapshots would be published after each PR merge.

**Comment by ligangty** [comment]
> > @rnc We have an internal indy to host all snapshot version with each PR build merging to publish dependency for internal usage. Of course the github action sounds good too, will add later.
> 
> What I do for other repos I control is simply publish each snapshot to sonatype snapshots repo via github actions - this removed the need for any internal jenkins/repository hosting/etc. And the snapshots would be published after each PR merge.

Ok. Seems this repo is not like commonjava repos which is mostly used in our internal team. I think the internal build process is not so important. I'll remove the jenkinsfile there.

**Comment by ligangty** [comment]
Dropped this PR.

**Pull request closed without merging**
